name: Build Sparkle

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Build Sparkle
  build:
    runs-on: ubuntu-latest

    # Run
    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build Sparkle
    - name: Build
      run: dotnet build --no-restore

    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # Publish to NuGet
  publish-nuget:
    runs-on: ubuntu-latest
    
    # Run
    steps:
      - uses: actions/checkout@v4
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build and pack NuGet package
      - name: Pack NuGet package
        if: github.event_name == 'release'
        run: dotnet pack src/Sparkle -p:PackageVersion=${{ github.event.release.tag_name }} --configuration Release --output nuget

      # Publish NuGet package
      - name: Publish NuGet package
        if: github.event_name == 'release'
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json